name: CI
on:
  push:
  pull_request:
defaults:
  run:
    shell: bash
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
jobs:
  rustfmt:
    name: Checks / Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.75.0
          components: rustfmt
      - name: Run
        run: make fmt
  clippy:
    name: Checks / Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.75.0
          components: clippy
      - name: Run
        run: make clippy
  tests:
    name: Tests / Run Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.75.0
      - name: Run
        run: make unit-tests

